"""empty message

Revision ID: 12fda70c20ec
Revises: 700540bee8bd
Create Date: 2022-05-22 21:18:08.125683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12fda70c20ec'
down_revision = '700540bee8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cancels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cancels', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
