"""empty message

Revision ID: fe57929c43e9
Revises: 12fda70c20ec
Create Date: 2022-05-23 18:33:45.163215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe57929c43e9'
down_revision = '12fda70c20ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file_path', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file_path')
    # ### end Alembic commands ###
